/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  TodoItem,
} from './components/todo-list/TodoList';

export namespace Components {
  interface JnTodoList {
    'items': TodoItem[];
  }
  interface JnToggleButton {
    'defaultToggled': boolean;
  }
}

declare global {


  interface HTMLJnTodoListElement extends Components.JnTodoList, HTMLStencilElement {}
  var HTMLJnTodoListElement: {
    prototype: HTMLJnTodoListElement;
    new (): HTMLJnTodoListElement;
  };

  interface HTMLJnToggleButtonElement extends Components.JnToggleButton, HTMLStencilElement {}
  var HTMLJnToggleButtonElement: {
    prototype: HTMLJnToggleButtonElement;
    new (): HTMLJnToggleButtonElement;
  };
  interface HTMLElementTagNameMap {
    'jn-todo-list': HTMLJnTodoListElement;
    'jn-toggle-button': HTMLJnToggleButtonElement;
  }
}

declare namespace LocalJSX {
  interface JnTodoList {
    'items'?: TodoItem[];
    'onAddItem'?: (event: CustomEvent<any>) => void;
    'onCompleteItem'?: (event: CustomEvent<number>) => void;
    'onUncompleteItem'?: (event: CustomEvent<number>) => void;
  }
  interface JnToggleButton {
    'defaultToggled'?: boolean;
  }

  interface IntrinsicElements {
    'jn-todo-list': JnTodoList;
    'jn-toggle-button': JnToggleButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'jn-todo-list': LocalJSX.JnTodoList & JSXBase.HTMLAttributes<HTMLJnTodoListElement>;
      'jn-toggle-button': LocalJSX.JnToggleButton & JSXBase.HTMLAttributes<HTMLJnToggleButtonElement>;
    }
  }
}


